/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fundamentoproyecto;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Osmin Tovar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setSize(957, 548);

        File archivoBinario = new File("productos.bin");

        if (!archivoBinario.exists()) {
            binario.guardarComoBinario("categoriaProductos.txt", "productos.bin");
        } else {
            System.out.println("⚠️ El archivo binario ya existe. No se ha sobrescrito.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrame_PaginaPrincipal = new javax.swing.JFrame();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JMenuBar_PaginaPrincipal = new javax.swing.JMenuBar();
        JMenu_Base = new javax.swing.JMenu();
        JMenu_Ficha = new javax.swing.JMenu();
        JFrame_Base = new javax.swing.JFrame();
        JPanel_Base = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JText_Usuario = new javax.swing.JTextField();
        JText_Contraseña = new javax.swing.JTextField();
        JText_Puerto = new javax.swing.JTextField();
        JText_Base = new javax.swing.JTextField();
        JText_Servidor = new javax.swing.JTextField();
        JButton_Conexion = new javax.swing.JButton();
        JButton_Conexion1 = new javax.swing.JButton();
        JLabel_Base = new javax.swing.JLabel();
        JFrame_Ficha = new javax.swing.JFrame();
        JTabPane_Vendedores = new javax.swing.JTabbedPane();
        JPanel_VendedoresImpresion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_ImpresionVendedores = new javax.swing.JTable();
        JLabel_Buscar = new javax.swing.JLabel();
        JText_BuscarVendedor = new javax.swing.JTextField();
        JLable_ImpresionVendedores = new javax.swing.JLabel();
        JTabPane_FichaPorVendedor = new javax.swing.JPanel();
        JLabel_FichaVendedor = new javax.swing.JLabel();
        JPanel_BuscarFicha = new javax.swing.JPanel();
        JText_BuscarFicha = new javax.swing.JTextField();
        JLabel_BuscarFicha = new javax.swing.JLabel();
        JLabel_TipoFicha = new javax.swing.JLabel();
        JLabel_Metas = new javax.swing.JLabel();
        JLabel_Bono = new javax.swing.JLabel();
        JLabel_Porcentajes = new javax.swing.JLabel();
        JLabel_FirmaPago = new javax.swing.JLabel();
        JText_TipoVendedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JArea_MetasFicha = new javax.swing.JTextArea();
        JText_Bono = new javax.swing.JTextField();
        JText_Firma = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTable_ficha = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        JComboBox_SucursalFicha = new javax.swing.JComboBox<>();
        JLabel_Ficha = new javax.swing.JLabel();
        JPanel_EditarVendedor = new javax.swing.JPanel();
        JLabel_EditarVendedorPrincipal = new javax.swing.JLabel();
        JLabel_SucursalEditar = new javax.swing.JLabel();
        JPanel_BuscarFicha1 = new javax.swing.JPanel();
        JLabel_BuscarFicha1 = new javax.swing.JLabel();
        JText_BuscarFicha1 = new javax.swing.JTextField();
        JButton_AgregarComision = new javax.swing.JButton();
        JButton_Editar = new javax.swing.JButton();
        JComboBox_SucursalEditar1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable_Productos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        JComboBox_Tipo = new javax.swing.JComboBox<>();
        JLabel_EditarVendedor = new javax.swing.JLabel();
        JFrame_NuevaCom = new javax.swing.JFrame();
        JPanel_NuevaCom = new javax.swing.JPanel();
        JLabel_ComisionEspecial = new javax.swing.JLabel();
        JLabel_PorCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        JText_PorcentajeCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        JLabel_NuevaCom = new javax.swing.JLabel();
        Button_IniciarSesion = new javax.swing.JButton();
        PaginaInicio = new javax.swing.JLabel();

        JFrame_PaginaPrincipal.setMinimumSize(new java.awt.Dimension(957, 569));

        PanelPrincipal.setMaximumSize(new java.awt.Dimension(957, 548));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(957, 548));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(957, 548));
        PanelPrincipal.setVerifyInputWhenFocusTarget(false);
        PanelPrincipal.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PaginaPrincipal2.png"))); // NOI18N
        PanelPrincipal.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 550);

        JMenu_Base.setText("Conectar a Base");
        JMenu_Base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_BaseMouseClicked(evt);
            }
        });
        JMenuBar_PaginaPrincipal.add(JMenu_Base);

        JMenu_Ficha.setText("Ficha de Vendedores");
        JMenu_Ficha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_FichaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JMenu_FichaMouseEntered(evt);
            }
        });
        JMenuBar_PaginaPrincipal.add(JMenu_Ficha);

        JFrame_PaginaPrincipal.setJMenuBar(JMenuBar_PaginaPrincipal);

        javax.swing.GroupLayout JFrame_PaginaPrincipalLayout = new javax.swing.GroupLayout(JFrame_PaginaPrincipal.getContentPane());
        JFrame_PaginaPrincipal.getContentPane().setLayout(JFrame_PaginaPrincipalLayout);
        JFrame_PaginaPrincipalLayout.setHorizontalGroup(
            JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
            .addGroup(JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_PaginaPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrame_PaginaPrincipalLayout.setVerticalGroup(
            JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_PaginaPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JFrame_Base.setMaximumSize(new java.awt.Dimension(734, 394));

        JPanel_Base.setMaximumSize(new java.awt.Dimension(734, 394));
        JPanel_Base.setMinimumSize(new java.awt.Dimension(734, 394));
        JPanel_Base.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña de la base:");
        JPanel_Base.add(jLabel3);
        jLabel3.setBounds(140, 210, 140, 19);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setText("Usuario de la base:");
        JPanel_Base.add(jLabel2);
        jLabel2.setBounds(140, 160, 130, 20);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Nombre de la base:");
        JPanel_Base.add(jLabel4);
        jLabel4.setBounds(140, 250, 130, 19);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setText("Conexion a la Base de Datos");
        JPanel_Base.add(jLabel1);
        jLabel1.setBounds(120, 80, 530, 70);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel5.setText("Puerto:");
        JPanel_Base.add(jLabel5);
        jLabel5.setBounds(140, 330, 41, 19);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel6.setText("Servidor:");
        JPanel_Base.add(jLabel6);
        jLabel6.setBounds(140, 290, 51, 19);

        JText_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Usuario);
        JText_Usuario.setBounds(310, 160, 270, 30);

        JText_Contraseña.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Contraseña);
        JText_Contraseña.setBounds(310, 200, 270, 30);

        JText_Puerto.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Puerto);
        JText_Puerto.setBounds(310, 330, 270, 30);

        JText_Base.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Base);
        JText_Base.setBounds(310, 250, 270, 30);

        JText_Servidor.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Servidor);
        JText_Servidor.setBounds(310, 290, 270, 30);

        JButton_Conexion.setBackground(new java.awt.Color(255, 255, 255));
        JButton_Conexion.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        JButton_Conexion.setText("Cargar Ventas");
        JButton_Conexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_ConexionMouseClicked(evt);
            }
        });
        JPanel_Base.add(JButton_Conexion);
        JButton_Conexion.setBounds(150, 390, 120, 40);

        JButton_Conexion1.setBackground(new java.awt.Color(255, 255, 255));
        JButton_Conexion1.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        JButton_Conexion1.setText("Cargar Clientes");
        JButton_Conexion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_Conexion1MouseClicked(evt);
            }
        });
        JPanel_Base.add(JButton_Conexion1);
        JButton_Conexion1.setBounds(430, 390, 120, 40);

        JLabel_Base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bases.jpg"))); // NOI18N
        JPanel_Base.add(JLabel_Base);
        JLabel_Base.setBounds(-4, 0, 740, 479);

        javax.swing.GroupLayout JFrame_BaseLayout = new javax.swing.GroupLayout(JFrame_Base.getContentPane());
        JFrame_Base.getContentPane().setLayout(JFrame_BaseLayout);
        JFrame_BaseLayout.setHorizontalGroup(
            JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_BaseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrame_BaseLayout.setVerticalGroup(
            JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_BaseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JFrame_Ficha.setMaximumSize(new java.awt.Dimension(957, 569));
        JFrame_Ficha.setMinimumSize(new java.awt.Dimension(957, 569));
        JFrame_Ficha.setPreferredSize(new java.awt.Dimension(957, 569));
        JFrame_Ficha.getContentPane().setLayout(null);

        JTabPane_Vendedores.setMaximumSize(new java.awt.Dimension(957, 569));
        JTabPane_Vendedores.setMinimumSize(new java.awt.Dimension(957, 569));
        JTabPane_Vendedores.setPreferredSize(new java.awt.Dimension(957, 569));
        JTabPane_Vendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabPane_VendedoresMouseClicked(evt);
            }
        });

        JPanel_VendedoresImpresion.setMaximumSize(new java.awt.Dimension(957, 569));
        JPanel_VendedoresImpresion.setMinimumSize(new java.awt.Dimension(957, 569));
        JPanel_VendedoresImpresion.setPreferredSize(new java.awt.Dimension(957, 569));
        JPanel_VendedoresImpresion.setLayout(null);

        JTable_ImpresionVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_ImpresionVendedores);

        JPanel_VendedoresImpresion.add(jScrollPane1);
        jScrollPane1.setBounds(40, 40, 540, 390);

        JLabel_Buscar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        JLabel_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lupa.png"))); // NOI18N
        JLabel_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabel_BuscarMouseClicked(evt);
            }
        });
        JPanel_VendedoresImpresion.add(JLabel_Buscar);
        JLabel_Buscar.setBounds(600, 40, 30, 30);
        JPanel_VendedoresImpresion.add(JText_BuscarVendedor);
        JText_BuscarVendedor.setBounds(640, 40, 230, 30);

        JLable_ImpresionVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vendedores.png"))); // NOI18N
        JPanel_VendedoresImpresion.add(JLable_ImpresionVendedores);
        JLable_ImpresionVendedores.setBounds(0, 0, 957, 548);

        JTabPane_Vendedores.addTab("Vendedores", JPanel_VendedoresImpresion);

        JTabPane_FichaPorVendedor.setLayout(null);

        JLabel_FichaVendedor.setFont(new java.awt.Font("Sylfaen", 0, 36)); // NOI18N
        JLabel_FichaVendedor.setText("Ficha de Vendedor");
        JTabPane_FichaPorVendedor.add(JLabel_FichaVendedor);
        JLabel_FichaVendedor.setBounds(330, 40, 340, 48);

        JPanel_BuscarFicha.setBackground(new java.awt.Color(255, 255, 255));

        JText_BuscarFicha.setBorder(null);

        JLabel_BuscarFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lupa.png"))); // NOI18N
        JLabel_BuscarFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabel_BuscarFichaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanel_BuscarFichaLayout = new javax.swing.GroupLayout(JPanel_BuscarFicha);
        JPanel_BuscarFicha.setLayout(JPanel_BuscarFichaLayout);
        JPanel_BuscarFichaLayout.setHorizontalGroup(
            JPanel_BuscarFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_BuscarFichaLayout.createSequentialGroup()
                .addComponent(JText_BuscarFicha, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_BuscarFicha))
        );
        JPanel_BuscarFichaLayout.setVerticalGroup(
            JPanel_BuscarFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_BuscarFichaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(JPanel_BuscarFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_BuscarFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_BuscarFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        JTabPane_FichaPorVendedor.add(JPanel_BuscarFicha);
        JPanel_BuscarFicha.setBounds(260, 90, 400, 30);

        JLabel_TipoFicha.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        JLabel_TipoFicha.setText("Tipo de Vendedor");
        JTabPane_FichaPorVendedor.add(JLabel_TipoFicha);
        JLabel_TipoFicha.setBounds(80, 210, 140, 19);

        JLabel_Metas.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        JLabel_Metas.setText("Metas del Vendedor");
        JTabPane_FichaPorVendedor.add(JLabel_Metas);
        JLabel_Metas.setBounds(80, 260, 114, 19);

        JLabel_Bono.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        JLabel_Bono.setText("Bonos por cumplimiento");
        JTabPane_FichaPorVendedor.add(JLabel_Bono);
        JLabel_Bono.setBounds(550, 170, 150, 19);

        JLabel_Porcentajes.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        JLabel_Porcentajes.setText("Porcentajes");
        JTabPane_FichaPorVendedor.add(JLabel_Porcentajes);
        JLabel_Porcentajes.setBounds(550, 230, 100, 14);

        JLabel_FirmaPago.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        JLabel_FirmaPago.setText("Firma de Autorizacion de Pago");
        JTabPane_FichaPorVendedor.add(JLabel_FirmaPago);
        JLabel_FirmaPago.setBounds(80, 500, 180, 19);
        JTabPane_FichaPorVendedor.add(JText_TipoVendedor);
        JText_TipoVendedor.setBounds(220, 210, 220, 30);

        JArea_MetasFicha.setColumns(20);
        JArea_MetasFicha.setRows(5);
        jScrollPane2.setViewportView(JArea_MetasFicha);

        JTabPane_FichaPorVendedor.add(jScrollPane2);
        jScrollPane2.setBounds(80, 300, 370, 170);
        JTabPane_FichaPorVendedor.add(JText_Bono);
        JText_Bono.setBounds(710, 170, 200, 30);

        JText_Firma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JText_FirmaActionPerformed(evt);
            }
        });
        JTabPane_FichaPorVendedor.add(JText_Firma);
        JText_Firma.setBounds(290, 490, 160, 30);

        JTable_ficha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Porcentaje", "Comision Calculada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(JTable_ficha);

        JTabPane_FichaPorVendedor.add(jScrollPane4);
        jScrollPane4.setBounds(630, 230, 290, 290);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel16.setText("Sucursal");
        JTabPane_FichaPorVendedor.add(jLabel16);
        jLabel16.setBounds(80, 170, 70, 19);

        JComboBox_SucursalFicha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kennedy", "San Angel", "Ruben Dario", "City Mall", " " }));
        JTabPane_FichaPorVendedor.add(JComboBox_SucursalFicha);
        JComboBox_SucursalFicha.setBounds(220, 160, 100, 30);

        JLabel_Ficha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ficha.png"))); // NOI18N
        JTabPane_FichaPorVendedor.add(JLabel_Ficha);
        JLabel_Ficha.setBounds(0, 0, 957, 548);

        JTabPane_Vendedores.addTab("Ficha Por Vendedor", JTabPane_FichaPorVendedor);

        JPanel_EditarVendedor.setMaximumSize(new java.awt.Dimension(957, 569));
        JPanel_EditarVendedor.setMinimumSize(new java.awt.Dimension(957, 569));
        JPanel_EditarVendedor.setPreferredSize(new java.awt.Dimension(957, 569));
        JPanel_EditarVendedor.setLayout(null);

        JLabel_EditarVendedorPrincipal.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        JLabel_EditarVendedorPrincipal.setText("Editar Comision Por Categoria de Producto");
        JPanel_EditarVendedor.add(JLabel_EditarVendedorPrincipal);
        JLabel_EditarVendedorPrincipal.setBounds(240, 110, 440, 33);

        JLabel_SucursalEditar.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        JLabel_SucursalEditar.setText("Sucursal");
        JPanel_EditarVendedor.add(JLabel_SucursalEditar);
        JLabel_SucursalEditar.setBounds(180, 190, 80, 19);

        JPanel_BuscarFicha1.setBackground(new java.awt.Color(255, 255, 255));

        JLabel_BuscarFicha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lupa.png"))); // NOI18N
        JLabel_BuscarFicha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabel_BuscarFicha1MouseClicked(evt);
            }
        });

        JText_BuscarFicha1.setBorder(null);

        javax.swing.GroupLayout JPanel_BuscarFicha1Layout = new javax.swing.GroupLayout(JPanel_BuscarFicha1);
        JPanel_BuscarFicha1.setLayout(JPanel_BuscarFicha1Layout);
        JPanel_BuscarFicha1Layout.setHorizontalGroup(
            JPanel_BuscarFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_BuscarFicha1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JText_BuscarFicha1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_BuscarFicha1))
        );
        JPanel_BuscarFicha1Layout.setVerticalGroup(
            JPanel_BuscarFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_BuscarFicha1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(JPanel_BuscarFicha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_BuscarFicha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_BuscarFicha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        JPanel_EditarVendedor.add(JPanel_BuscarFicha1);
        JPanel_BuscarFicha1.setBounds(260, 150, 400, 30);

        JButton_AgregarComision.setText("Agregar Tipo de Comision Especial");
        JButton_AgregarComision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_AgregarComisionMouseClicked(evt);
            }
        });
        JPanel_EditarVendedor.add(JButton_AgregarComision);
        JButton_AgregarComision.setBounds(520, 450, 200, 40);

        JButton_Editar.setText("Editar");
        JButton_Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_EditarMouseClicked(evt);
            }
        });
        JPanel_EditarVendedor.add(JButton_Editar);
        JButton_Editar.setBounds(360, 450, 80, 40);

        JComboBox_SucursalEditar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kennedy", "San Angel", "Ruben Dario", "City Mall" }));
        JPanel_EditarVendedor.add(JComboBox_SucursalEditar1);
        JComboBox_SucursalEditar1.setBounds(180, 210, 110, 30);

        JTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JTable_Productos);

        JPanel_EditarVendedor.add(jScrollPane3);
        jScrollPane3.setBounds(360, 200, 360, 240);

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel15.setText("Tipo de Vendedor");
        JPanel_EditarVendedor.add(jLabel15);
        jLabel15.setBounds(180, 270, 120, 19);

        JComboBox_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pista", "Mayoreo", "Redes Sociales" }));
        JPanel_EditarVendedor.add(JComboBox_Tipo);
        JComboBox_Tipo.setBounds(180, 310, 100, 30);

        JLabel_EditarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar_Vendedor.png"))); // NOI18N
        JLabel_EditarVendedor.setMaximumSize(new java.awt.Dimension(957, 569));
        JLabel_EditarVendedor.setMinimumSize(new java.awt.Dimension(957, 569));
        JLabel_EditarVendedor.setPreferredSize(new java.awt.Dimension(957, 569));
        JPanel_EditarVendedor.add(JLabel_EditarVendedor);
        JLabel_EditarVendedor.setBounds(0, 0, 957, 569);

        JTabPane_Vendedores.addTab("Comision Por Producto", JPanel_EditarVendedor);

        JFrame_Ficha.getContentPane().add(JTabPane_Vendedores);
        JTabPane_Vendedores.setBounds(0, 0, 957, 569);

        JFrame_NuevaCom.setMaximumSize(new java.awt.Dimension(734, 394));

        JPanel_NuevaCom.setMaximumSize(new java.awt.Dimension(734, 394));
        JPanel_NuevaCom.setMinimumSize(new java.awt.Dimension(734, 394));
        JPanel_NuevaCom.setLayout(null);

        JLabel_ComisionEspecial.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        JLabel_ComisionEspecial.setText("Agregar Comision Especial");
        JPanel_NuevaCom.add(JLabel_ComisionEspecial);
        JLabel_ComisionEspecial.setBounds(220, 20, 290, 60);

        JLabel_PorCliente.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        JLabel_PorCliente.setText("Por Cliente");
        JPanel_NuevaCom.add(JLabel_PorCliente);
        JLabel_PorCliente.setBounds(120, 120, 100, 24);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setText("Por Venta Indirecta");
        JPanel_NuevaCom.add(jLabel8);
        jLabel8.setBounds(490, 110, 160, 24);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setText("Comision");
        JPanel_NuevaCom.add(jLabel9);
        jLabel9.setBounds(70, 240, 120, 19);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kennedy", "San Angel", "Ruben Dario", "City Mall" }));
        JPanel_NuevaCom.add(jComboBox1);
        jComboBox1.setBounds(540, 320, 140, 30);

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("Tipo de Cliente");
        JPanel_NuevaCom.add(jLabel10);
        jLabel10.setBounds(70, 180, 120, 19);
        JPanel_NuevaCom.add(JText_PorcentajeCliente);
        JText_PorcentajeCliente.setBounds(200, 240, 140, 30);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setText("Vendedor Del que Recibe Comision");
        JPanel_NuevaCom.add(jLabel11);
        jLabel11.setBounds(470, 150, 200, 19);
        JPanel_NuevaCom.add(jTextField2);
        jTextField2.setBounds(450, 180, 230, 30);

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel12.setText("Comision");
        JPanel_NuevaCom.add(jLabel12);
        jLabel12.setBounds(450, 250, 70, 19);
        JPanel_NuevaCom.add(jTextField3);
        jTextField3.setBounds(540, 250, 140, 30);

        jButton1.setText("Agregar Comision");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        JPanel_NuevaCom.add(jButton1);
        jButton1.setBounds(340, 410, 117, 30);

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel13.setText("Sucursal");
        JPanel_NuevaCom.add(jLabel13);
        jLabel13.setBounds(80, 320, 70, 19);

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel14.setText("Sucursal");
        JPanel_NuevaCom.add(jLabel14);
        jLabel14.setBounds(460, 330, 50, 19);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JPanel_NuevaCom.add(jComboBox2);
        jComboBox2.setBounds(200, 180, 140, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kennedy", "San Angel", "Ruben Dario", "City Mall" }));
        JPanel_NuevaCom.add(jComboBox3);
        jComboBox3.setBounds(200, 320, 140, 30);

        jCheckBox1.setText("Comision Por Todo Lo Vendido");
        jCheckBox1.setToolTipText("");
        JPanel_NuevaCom.add(jCheckBox1);
        jCheckBox1.setBounds(530, 50, 180, 23);

        jCheckBox2.setText("Monto Total del Periodo");
        jCheckBox2.setToolTipText("");
        JPanel_NuevaCom.add(jCheckBox2);
        jCheckBox2.setBounds(530, 20, 160, 23);

        JLabel_NuevaCom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diferetnesComisiones.png"))); // NOI18N
        JPanel_NuevaCom.add(JLabel_NuevaCom);
        JLabel_NuevaCom.setBounds(-4, 0, 740, 479);

        javax.swing.GroupLayout JFrame_NuevaComLayout = new javax.swing.GroupLayout(JFrame_NuevaCom.getContentPane());
        JFrame_NuevaCom.getContentPane().setLayout(JFrame_NuevaComLayout);
        JFrame_NuevaComLayout.setHorizontalGroup(
            JFrame_NuevaComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrame_NuevaComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_NuevaComLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel_NuevaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrame_NuevaComLayout.setVerticalGroup(
            JFrame_NuevaComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrame_NuevaComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_NuevaComLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel_NuevaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jframe");
        getContentPane().setLayout(null);

        Button_IniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        Button_IniciarSesion.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Button_IniciarSesion.setText("Iniciar Sesion");
        Button_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_IniciarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(Button_IniciarSesion);
        Button_IniciarSesion.setBounds(220, 430, 200, 50);

        PaginaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bienvenido.png"))); // NOI18N
        getContentPane().add(PaginaInicio);
        PaginaInicio.setBounds(0, 0, 957, 548);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_IniciarSesionMouseClicked
        this.setVisible(false);
        PanelPrincipal.setLayout(null);
        PanelPrincipal.setSize(957, 548);

        JFrame_PaginaPrincipal.setSize(957, 548);
        JFrame_PaginaPrincipal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JFrame_PaginaPrincipal.setLocationRelativeTo(null);
        JFrame_PaginaPrincipal.setLayout(null);

        JFrame_PaginaPrincipal.add(PanelPrincipal);
// PanelPrincipal.setBounds(...) → ¡ya no es necesario!
        JFrame_PaginaPrincipal.setVisible(true);

    }//GEN-LAST:event_Button_IniciarSesionMouseClicked

    private void JButton_ConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_ConexionMouseClicked
        // TODO add your handling code here:
        String nombre = JText_Usuario.getText();
        String contraseña = JText_Contraseña.getText();
        String base = JText_Base.getText();
        String servidor = JText_Servidor.getText();
        String puerto = JText_Puerto.getText();

        sql.setNombreBase(base);
        sql.setPASSWORD(contraseña);
        sql.setUSER(nombre);
        sql.setServidor(servidor);
        sql.setPuerto(puerto);

        conn = sql.conect();

        //Cargar vendedor
        HashMap<String, Vendedor> vendedores = sql.cargarVendedores(conn);
        File archivo = new File("vendedores.bin");
        if (!archivo.exists()) {
            binario.escribirArchivo(vendedores);
            new Thread(() -> {
                System.out.println("⏳ Consultando base de datos...");
                sql.cargarventas("vendedores.bin", conn);
                System.out.println("✅ Consulta finalizada y binario actualizado.");
            }).start();
        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "El archivo ya existe. ¿Deseas sobrescribirlo?", "Archivo existente", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                binario.escribirArchivo(vendedores);
                System.out.println("✅ Archivo sobrescrito.");
            } else {
                System.out.println("❌ No se modificó el archivo.");
            }
        }
    }//GEN-LAST:event_JButton_ConexionMouseClicked

    private void JMenu_BaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_BaseMouseClicked
        // TODO add your handling code here:
        JPanel_Base.setLayout(null);
        JPanel_Base.setSize(736, 479);

        JFrame_Base.setSize(736, 479);
        JFrame_Base.setLocationRelativeTo(null);
        JFrame_Base.setLayout(null);
        JFrame_Base.add(JPanel_Base);
        JFrame_Base.setVisible(true);

    }//GEN-LAST:event_JMenu_BaseMouseClicked

    private void JMenu_FichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_FichaMouseClicked
        // Tablas
        binario.editarTabla(JTable_ImpresionVendedores);
        cargarProductos(JTable_Productos, "productos.bin");
        //Paneles
        JPanel_VendedoresImpresion.setLayout(null);
        JPanel_VendedoresImpresion.setSize(736, 479);

        JFrame_Ficha.setSize(736, 479);
        JFrame_Ficha.setLocationRelativeTo(null);
        JFrame_Ficha.setLayout(null);
        JFrame_Ficha.add(JTabPane_Vendedores);
        JFrame_Ficha.setVisible(true);

    }//GEN-LAST:event_JMenu_FichaMouseClicked

    private void JMenu_FichaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_FichaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenu_FichaMouseEntered

    private void JTabPane_VendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabPane_VendedoresMouseClicked
        // TODO add your handling code here:
        binario.editarTabla(JTable_ImpresionVendedores);
    }//GEN-LAST:event_JTabPane_VendedoresMouseClicked

    private void JButton_EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_EditarMouseClicked
        // TODO add your handling code here:
        if (JComboBox_Tipo.getSelectedItem().equals("Pista")) {
            vendedorActivo.getTipo().add("Pista");
            editarPorCategoria();

        } else if (JComboBox_Tipo.getSelectedItem().equals("Mayoreo")) {
            vendedorActivo.getTipo().add("Mayoreo");
            editarPorCategoria();
        } else if (JComboBox_Tipo.getSelectedItem().equals("Redes Sociales")) {
            vendedorActivo.getTipo().add("Redes Sociales");
            editarPorCategoria();
        }
        if (vendedorActivo != null) {
            binario.actualizarArchivo(vendedorActivo);
            System.out.println(vendedorActivo);
            JOptionPane.showMessageDialog(null, "✅ Archivo actualizado correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "❌ No se puede actualizar: el vendedor está vacío o no seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JButton_EditarMouseClicked

    private void JButton_AgregarComisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_AgregarComisionMouseClicked
        // TODO add your handling code here:
        JPanel_NuevaCom.setLayout(null);
        JPanel_NuevaCom.setSize(736, 479);

        JFrame_NuevaCom.setSize(736, 479);
        JFrame_NuevaCom.setLocationRelativeTo(null);
        JFrame_NuevaCom.setLayout(null);
        JFrame_NuevaCom.add(JPanel_NuevaCom);
        JFrame_NuevaCom.setVisible(true);
    }//GEN-LAST:event_JButton_AgregarComisionMouseClicked

    private void JLabel_BuscarFicha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabel_BuscarFicha1MouseClicked
        // TODO add your handling code here:
        String nombre = JText_BuscarFicha1.getText();
        vendedorActivo = binario.buscarVendedor(nombre);
        System.out.println(vendedorActivo);

        if (vendedorActivo != null) {
            JOptionPane.showMessageDialog(null,
                    "✅ Vendedor encontrado:\nID: " + vendedorActivo.getId() + "\nNombre: " + vendedorActivo.getNombre(),
                    "Resultado de búsqueda",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "❌ No se encontró ningún vendedor con el nombre: " + nombre,
                    "Sin resultados",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_JLabel_BuscarFicha1MouseClicked

    private void JLabel_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabel_BuscarMouseClicked
        // TODO add your handling code here:
        binario.buscarYMostrarVendedorEnTabla(JText_BuscarVendedor.getText(), JTable_ImpresionVendedores);
    }//GEN-LAST:event_JLabel_BuscarMouseClicked

    private void JLabel_BuscarFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabel_BuscarFichaMouseClicked
        // TODO add your handling code here:
        String nombre = JText_BuscarFicha.getText();
        String sucursal = "";
        switch ((String) JComboBox_SucursalEditar1.getSelectedItem()) {
            case "Kennedy": {
                sucursal = "1";
                break;
            }
            case "San Angel": {
                sucursal = "2";
                break;
            }
            case "Ruben Dario": {
                sucursal = "3";
                break;
            }
            case "City Mall": {
                sucursal = "4";
                break;
            }
            default:
                break;
        }
        int indexDeLaInformacion = 0;

        vendedorActivo = binario.buscarVendedor(nombre);

        for (int i = 0; i < vendedorActivo.getSucursal().size(); i++) {
            if (vendedorActivo.getSucursal().get(i).equalsIgnoreCase(sucursal)) {
                indexDeLaInformacion = i;
            }
        }

        JText_TipoVendedor.setText(vendedorActivo.getTipo().get(indexDeLaInformacion));
        Llenar_Tabla_Ficha(JTable_ficha, "vendedores.bin", indexDeLaInformacion);
    }//GEN-LAST:event_JLabel_BuscarFichaMouseClicked

    private void JText_FirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JText_FirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JText_FirmaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void JButton_Conexion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_Conexion1MouseClicked
        // TODO add your handling code here:
        new Thread(() -> {
            System.out.println("⏳ Consultando base de datos...");
            sql.cargarClientes("vendedores.bin", conn);
            System.out.println("✅ Consulta finalizada y binario actualizado.");
            binario.leerArchivo();
        }).start();
    }//GEN-LAST:event_JButton_Conexion1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_IniciarSesion;
    private javax.swing.JTextArea JArea_MetasFicha;
    private javax.swing.JButton JButton_AgregarComision;
    private javax.swing.JButton JButton_Conexion;
    private javax.swing.JButton JButton_Conexion1;
    private javax.swing.JButton JButton_Editar;
    private javax.swing.JComboBox<String> JComboBox_SucursalEditar1;
    private javax.swing.JComboBox<String> JComboBox_SucursalFicha;
    private javax.swing.JComboBox<String> JComboBox_Tipo;
    private javax.swing.JFrame JFrame_Base;
    private javax.swing.JFrame JFrame_Ficha;
    private javax.swing.JFrame JFrame_NuevaCom;
    private javax.swing.JFrame JFrame_PaginaPrincipal;
    private javax.swing.JLabel JLabel_Base;
    private javax.swing.JLabel JLabel_Bono;
    private javax.swing.JLabel JLabel_Buscar;
    private javax.swing.JLabel JLabel_BuscarFicha;
    private javax.swing.JLabel JLabel_BuscarFicha1;
    private javax.swing.JLabel JLabel_ComisionEspecial;
    private javax.swing.JLabel JLabel_EditarVendedor;
    private javax.swing.JLabel JLabel_EditarVendedorPrincipal;
    private javax.swing.JLabel JLabel_Ficha;
    private javax.swing.JLabel JLabel_FichaVendedor;
    private javax.swing.JLabel JLabel_FirmaPago;
    private javax.swing.JLabel JLabel_Metas;
    private javax.swing.JLabel JLabel_NuevaCom;
    private javax.swing.JLabel JLabel_PorCliente;
    private javax.swing.JLabel JLabel_Porcentajes;
    private javax.swing.JLabel JLabel_SucursalEditar;
    private javax.swing.JLabel JLabel_TipoFicha;
    private javax.swing.JLabel JLable_ImpresionVendedores;
    private javax.swing.JMenuBar JMenuBar_PaginaPrincipal;
    private javax.swing.JMenu JMenu_Base;
    private javax.swing.JMenu JMenu_Ficha;
    private javax.swing.JPanel JPanel_Base;
    private javax.swing.JPanel JPanel_BuscarFicha;
    private javax.swing.JPanel JPanel_BuscarFicha1;
    private javax.swing.JPanel JPanel_EditarVendedor;
    private javax.swing.JPanel JPanel_NuevaCom;
    private javax.swing.JPanel JPanel_VendedoresImpresion;
    private javax.swing.JPanel JTabPane_FichaPorVendedor;
    private javax.swing.JTabbedPane JTabPane_Vendedores;
    private javax.swing.JTable JTable_ImpresionVendedores;
    private javax.swing.JTable JTable_Productos;
    private javax.swing.JTable JTable_ficha;
    private javax.swing.JTextField JText_Base;
    private javax.swing.JTextField JText_Bono;
    private javax.swing.JTextField JText_BuscarFicha;
    private javax.swing.JTextField JText_BuscarFicha1;
    private javax.swing.JTextField JText_BuscarVendedor;
    private javax.swing.JTextField JText_Contraseña;
    private javax.swing.JTextField JText_Firma;
    private javax.swing.JTextField JText_PorcentajeCliente;
    private javax.swing.JTextField JText_Puerto;
    private javax.swing.JTextField JText_Servidor;
    private javax.swing.JTextField JText_TipoVendedor;
    private javax.swing.JTextField JText_Usuario;
    private javax.swing.JLabel PaginaInicio;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    //Variables Globales
    SQLManagement sql = new SQLManagement();
    Connection conn = null;

    ManejarArchivos binario = new ManejarArchivos("vendedores.bin");
    Vendedor vendedorActivo = new Vendedor();

    //Funciones
    public void cargarProductos(JTable tabla, String rutaBinario) {
        File archivo = new File(rutaBinario);

        if (!archivo.exists()) {
            System.out.println("⚠️ El archivo binario no existe.");
            return;
        }

        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(archivo))) {
            ArrayList<Producto> productos = (ArrayList<Producto>) ois.readObject();

            String[] columnas = {"Codigo", "Categoria", "Comision"};
            DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

            for (Producto p : productos) {
                Object[] fila = {p.getId(), p.getCategoria()};
                modelo.addRow(fila);
            }

            tabla.setModel(modelo);
            System.out.println("✅ Datos cargados en la tabla.");

        } catch (IOException | ClassNotFoundException e) {
            System.err.println("❌ Error al leer el archivo: " + e.getMessage());
        }
    }

    public ArrayList<Producto> obtenerProductosDesdeTabla(JTable tabla) {
        ArrayList<Producto> listaProductos = new ArrayList<>();

        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int filas = modelo.getRowCount();

        for (int i = 0; i < filas; i++) {
            try {
                int id = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                String categoria = modelo.getValueAt(i, 1).toString();
                double porcentajeComision = Double.parseDouble(modelo.getValueAt(i, 2).toString());

                Producto producto = new Producto(categoria, id);
                producto.setPorcentajeComision(porcentajeComision);
                listaProductos.add(producto);
            } catch (NumberFormatException e) {
                System.err.println("⚠️ Error al convertir número en la fila " + i + ": " + e.getMessage());
            } catch (Exception e) {
                System.err.println("⚠️ Error general en la fila " + i + ": " + e.getMessage());
            }
        }

        return listaProductos;
    }

    public void editarPorCategoria() {
        switch ((String) JComboBox_SucursalEditar1.getSelectedItem()) {
            case "Kennedy": {
                ArrayList<Producto> productosDelVendedor = obtenerProductosDesdeTabla(JTable_Productos);
                PorProducto p = new PorProducto(productosDelVendedor, 1);
                vendedorActivo.getComisiones().add(p);
                vendedorActivo.getSucursal().add("1");
                break;
            }
            case "San Angel": {
                ArrayList<Producto> productosDelVendedor = obtenerProductosDesdeTabla(JTable_Productos);
                PorProducto p = new PorProducto(productosDelVendedor, 2);
                vendedorActivo.getComisiones().add(p);
                vendedorActivo.getSucursal().add("2");
                break;
            }
            case "Ruben Dario": {
                ArrayList<Producto> productosDelVendedor = obtenerProductosDesdeTabla(JTable_Productos);
                PorProducto p = new PorProducto(productosDelVendedor, 3);
                vendedorActivo.getComisiones().add(p);
                vendedorActivo.getSucursal().add("3");
                break;
            }
            case "City Mall": {
                ArrayList<Producto> productosDelVendedor = obtenerProductosDesdeTabla(JTable_Productos);
                PorProducto p = new PorProducto(productosDelVendedor, 4);
                vendedorActivo.getComisiones().add(p);
                vendedorActivo.getSucursal().add("4");
                break;
            }
            default:
                break;
        }
    }

    public void Llenar_Tabla_Ficha(JTable tabla, String rutaBinario, int localizacion) {
        Map<String, Vendedor> vendedores;

        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(rutaBinario))) {
            vendedores = (Map<String, Vendedor>) ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("❌ Error al leer binario: " + e.getMessage());
            return;
        }

        // Si quieres usar el vendedorActivo que viene de afuera, puedes ignorar el mapa que leíste.
        // O si quieres usar un vendedor del archivo, obténlo de 'vendedores' aquí.
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Tipo");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Comisión Calculada");

        // Verificar que vendedorActivo no sea null y tenga comisiones
        if (vendedorActivo != null && vendedorActivo.getComisiones() != null) {
            Comision com = vendedorActivo.getComisiones().get(localizacion);
            if (com instanceof PorProducto) {
                PorProducto porProducto = (PorProducto) com;

                // Recorrer la lista de comisiones por producto dentro de esta comision
                for (Producto detalle : porProducto.getComisionPorProducto()) {
                    modelo.addRow(new Object[]{
                        detalle.getCategoria(),
                        detalle.getPorcentajeComision(),
                        porProducto.calcularComisionPorProducto(vendedorActivo.getVentas(), detalle.getCategoria()) // o si es por detalle, ajusta aquí
                    });
                }

                // Puedes agregar else if para otros tipos de comisiones si hay
            }
        }

        tabla.setModel(modelo);
    }

}
