/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fundamentoproyecto;

import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author Osmin Tovar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setSize(957, 548);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrame_PaginaPrincipal = new javax.swing.JFrame();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JMenuBar_PaginaPrincipal = new javax.swing.JMenuBar();
        JMenu_Base = new javax.swing.JMenu();
        JMenu_Ficha = new javax.swing.JMenu();
        JFrame_Base = new javax.swing.JFrame();
        JPanel_Base = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JText_Usuario = new javax.swing.JTextField();
        JText_Contraseña = new javax.swing.JTextField();
        JText_Puerto = new javax.swing.JTextField();
        JText_Base = new javax.swing.JTextField();
        JText_Servidor = new javax.swing.JTextField();
        JButton_Conexion = new javax.swing.JButton();
        JLabel_Base = new javax.swing.JLabel();
        JFrame_Ficha = new javax.swing.JFrame();
        JTabPane_Vendedores = new javax.swing.JTabbedPane();
        JPanel_VendedoresImpresion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_ImpresionVendedores = new javax.swing.JTable();
        JLabel_Buscar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        JLable_ImpresionVendedores = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Button_IniciarSesion = new javax.swing.JButton();
        PaginaInicio = new javax.swing.JLabel();

        JFrame_PaginaPrincipal.setMinimumSize(new java.awt.Dimension(957, 569));

        PanelPrincipal.setMaximumSize(new java.awt.Dimension(957, 548));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(957, 548));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(957, 548));
        PanelPrincipal.setVerifyInputWhenFocusTarget(false);
        PanelPrincipal.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PaginaPrincipal2.png"))); // NOI18N
        PanelPrincipal.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 550);

        JMenu_Base.setText("Conectar a Base");
        JMenu_Base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_BaseMouseClicked(evt);
            }
        });
        JMenuBar_PaginaPrincipal.add(JMenu_Base);

        JMenu_Ficha.setText("Ficha de Vendedores");
        JMenu_Ficha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_FichaMouseClicked(evt);
            }
        });
        JMenuBar_PaginaPrincipal.add(JMenu_Ficha);

        JFrame_PaginaPrincipal.setJMenuBar(JMenuBar_PaginaPrincipal);

        javax.swing.GroupLayout JFrame_PaginaPrincipalLayout = new javax.swing.GroupLayout(JFrame_PaginaPrincipal.getContentPane());
        JFrame_PaginaPrincipal.getContentPane().setLayout(JFrame_PaginaPrincipalLayout);
        JFrame_PaginaPrincipalLayout.setHorizontalGroup(
            JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
            .addGroup(JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_PaginaPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrame_PaginaPrincipalLayout.setVerticalGroup(
            JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(JFrame_PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_PaginaPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JFrame_Base.setMaximumSize(new java.awt.Dimension(734, 394));

        JPanel_Base.setMaximumSize(new java.awt.Dimension(734, 394));
        JPanel_Base.setMinimumSize(new java.awt.Dimension(734, 394));
        JPanel_Base.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña de la base:");
        JPanel_Base.add(jLabel3);
        jLabel3.setBounds(140, 210, 140, 19);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setText("Usuario de la base:");
        JPanel_Base.add(jLabel2);
        jLabel2.setBounds(140, 160, 130, 20);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Nombre de la base:");
        JPanel_Base.add(jLabel4);
        jLabel4.setBounds(140, 250, 130, 19);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setText("Conexion a la Base de Datos");
        JPanel_Base.add(jLabel1);
        jLabel1.setBounds(120, 80, 530, 70);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel5.setText("Puerto:");
        JPanel_Base.add(jLabel5);
        jLabel5.setBounds(140, 330, 41, 19);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel6.setText("Servidor:");
        JPanel_Base.add(jLabel6);
        jLabel6.setBounds(140, 290, 51, 19);

        JText_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Usuario);
        JText_Usuario.setBounds(310, 160, 270, 30);

        JText_Contraseña.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Contraseña);
        JText_Contraseña.setBounds(310, 200, 270, 30);

        JText_Puerto.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Puerto);
        JText_Puerto.setBounds(310, 330, 270, 30);

        JText_Base.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Base);
        JText_Base.setBounds(310, 250, 270, 30);

        JText_Servidor.setForeground(new java.awt.Color(204, 204, 204));
        JPanel_Base.add(JText_Servidor);
        JText_Servidor.setBounds(310, 290, 270, 30);

        JButton_Conexion.setBackground(new java.awt.Color(255, 255, 255));
        JButton_Conexion.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        JButton_Conexion.setText("Conectar Base");
        JButton_Conexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_ConexionMouseClicked(evt);
            }
        });
        JPanel_Base.add(JButton_Conexion);
        JButton_Conexion.setBounds(140, 380, 120, 25);

        JLabel_Base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bases.jpg"))); // NOI18N
        JPanel_Base.add(JLabel_Base);
        JLabel_Base.setBounds(-4, 0, 740, 479);

        javax.swing.GroupLayout JFrame_BaseLayout = new javax.swing.GroupLayout(JFrame_Base.getContentPane());
        JFrame_Base.getContentPane().setLayout(JFrame_BaseLayout);
        JFrame_BaseLayout.setHorizontalGroup(
            JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_BaseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrame_BaseLayout.setVerticalGroup(
            JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrame_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrame_BaseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JFrame_Ficha.setMaximumSize(new java.awt.Dimension(957, 569));
        JFrame_Ficha.setMinimumSize(new java.awt.Dimension(957, 569));
        JFrame_Ficha.setPreferredSize(new java.awt.Dimension(957, 569));
        JFrame_Ficha.getContentPane().setLayout(null);

        JTabPane_Vendedores.setMaximumSize(new java.awt.Dimension(957, 569));
        JTabPane_Vendedores.setMinimumSize(new java.awt.Dimension(957, 569));
        JTabPane_Vendedores.setPreferredSize(new java.awt.Dimension(957, 569));

        JPanel_VendedoresImpresion.setMaximumSize(new java.awt.Dimension(957, 569));
        JPanel_VendedoresImpresion.setMinimumSize(new java.awt.Dimension(957, 569));
        JPanel_VendedoresImpresion.setPreferredSize(new java.awt.Dimension(957, 569));
        JPanel_VendedoresImpresion.setLayout(null);

        JTable_ImpresionVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_ImpresionVendedores);

        JPanel_VendedoresImpresion.add(jScrollPane1);
        jScrollPane1.setBounds(40, 40, 540, 390);

        JLabel_Buscar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        JLabel_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lupa.png"))); // NOI18N
        JPanel_VendedoresImpresion.add(JLabel_Buscar);
        JLabel_Buscar.setBounds(600, 40, 30, 30);
        JPanel_VendedoresImpresion.add(jTextField1);
        jTextField1.setBounds(640, 40, 230, 30);

        JLable_ImpresionVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vendedores.png"))); // NOI18N
        JPanel_VendedoresImpresion.add(JLable_ImpresionVendedores);
        JLable_ImpresionVendedores.setBounds(0, 0, 957, 548);

        JTabPane_Vendedores.addTab("Vendedores", JPanel_VendedoresImpresion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        JTabPane_Vendedores.addTab("Ficha Por Vendedor", jPanel2);

        JFrame_Ficha.getContentPane().add(JTabPane_Vendedores);
        JTabPane_Vendedores.setBounds(0, 0, 957, 569);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jframe");
        getContentPane().setLayout(null);

        Button_IniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        Button_IniciarSesion.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Button_IniciarSesion.setText("Iniciar Sesion");
        Button_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_IniciarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(Button_IniciarSesion);
        Button_IniciarSesion.setBounds(220, 430, 200, 50);

        PaginaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bienvenido.png"))); // NOI18N
        getContentPane().add(PaginaInicio);
        PaginaInicio.setBounds(0, 0, 957, 548);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_IniciarSesionMouseClicked
        this.setVisible(false);
        PanelPrincipal.setLayout(null);
        PanelPrincipal.setSize(957, 548);

        JFrame_PaginaPrincipal.setSize(957, 548);
        JFrame_PaginaPrincipal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JFrame_PaginaPrincipal.setLocationRelativeTo(null);
        JFrame_PaginaPrincipal.setLayout(null);

        JFrame_PaginaPrincipal.add(PanelPrincipal);
// PanelPrincipal.setBounds(...) → ¡ya no es necesario!
        JFrame_PaginaPrincipal.setVisible(true);

    }//GEN-LAST:event_Button_IniciarSesionMouseClicked

    private void JButton_ConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_ConexionMouseClicked
        // TODO add your handling code here:
        String nombre = JText_Usuario.getText();
        String contraseña = JText_Contraseña.getText();
        String base = JText_Base.getText();
        String servidor = JText_Servidor.getText();
        String puerto = JText_Puerto.getText();
        
        sql.setNombreBase(base);
        sql.setPASSWORD(contraseña);
        sql.setUSER(nombre);
        sql.setServidor(servidor);
        sql.setPuerto(puerto);
        
         conn = sql.conect();
        
    }//GEN-LAST:event_JButton_ConexionMouseClicked

    private void JMenu_BaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_BaseMouseClicked
        // TODO add your handling code here:
        JPanel_Base.setLayout(null);
        JPanel_Base.setSize(736, 479);

        JFrame_Base.setSize(736, 479);
        JFrame_Base.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JFrame_Base.setLocationRelativeTo(null);
        JFrame_Base.setLayout(null);
        JFrame_Base.add(JPanel_Base); // ← Asegúrate de que aquí estás agregando el JPanel correcto
        JFrame_Base.setVisible(true);

    }//GEN-LAST:event_JMenu_BaseMouseClicked

    private void JMenu_FichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_FichaMouseClicked
        // TODO add your handling code here:
        sql.llenarTabla(conn, JTable_ImpresionVendedores);
        
        JPanel_VendedoresImpresion.setLayout(null);
        JPanel_VendedoresImpresion.setSize(736, 479);

        JFrame_Ficha.setSize(736, 479);
        JFrame_Ficha.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JFrame_Ficha.setLocationRelativeTo(null);
        JFrame_Ficha.setLayout(null);
        JFrame_Ficha.add(JTabPane_Vendedores); // ← Asegúrate de que aquí estás agregando el JPanel correcto
        JFrame_Ficha.setVisible(true);

    }//GEN-LAST:event_JMenu_FichaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_IniciarSesion;
    private javax.swing.JButton JButton_Conexion;
    private javax.swing.JFrame JFrame_Base;
    private javax.swing.JFrame JFrame_Ficha;
    private javax.swing.JFrame JFrame_PaginaPrincipal;
    private javax.swing.JLabel JLabel_Base;
    private javax.swing.JLabel JLabel_Buscar;
    private javax.swing.JLabel JLable_ImpresionVendedores;
    private javax.swing.JMenuBar JMenuBar_PaginaPrincipal;
    private javax.swing.JMenu JMenu_Base;
    private javax.swing.JMenu JMenu_Ficha;
    private javax.swing.JPanel JPanel_Base;
    private javax.swing.JPanel JPanel_VendedoresImpresion;
    private javax.swing.JTabbedPane JTabPane_Vendedores;
    private javax.swing.JTable JTable_ImpresionVendedores;
    private javax.swing.JTextField JText_Base;
    private javax.swing.JTextField JText_Contraseña;
    private javax.swing.JTextField JText_Puerto;
    private javax.swing.JTextField JText_Servidor;
    private javax.swing.JTextField JText_Usuario;
    private javax.swing.JLabel PaginaInicio;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    //Variables Globales
    SQLManagement sql = new SQLManagement();
    Connection conn = null;

}
